version: '3.6'

services:
    app:
        build: .
        ports:
            - "8000:8000"
#        command: php artisan serve --host 0.0.0.0
        working_dir: /usr/src/laravel-react-recipe-book
        depends_on:
            - postgres
            - web
        volumes:
            - ./:/usr/src/laravel-react-recipe-book
    postgres:
        image: postgres:14
        #    build: ./postgres
        environment:
            POSTGRES_USER: chef
            POSTGRES_PASSWORD: SUPERsecret!!!:-)
            POSTGRES_DB: recipe-book
            POSTGRES_HOST: postgres
        ports:
            - "5432:5432"
    web:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./public:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf:ro

