version: '3.6'

services:
    web:
        build: ./
        ports:
            - 8000:8000
        volumes:
            - ./:/app
    postgres:
        image: postgres:14
        #    build: ./postgres
        environment:
            POSTGRES_USER: chef
            POSTGRES_PASSWORD: SUPERsecret!!!:-)
            POSTGRES_DB: recipe-book
            POSTGRES_HOST: postgres
        ports:
            - "5432:5432"

