version: '3.6'

services:
    app:
        build: .
        ports:
            - "9000:9000"
        depends_on:
            - postgres
        tty: true
        volumes:
            - ./:/var/www/html
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: postgres
            DB_PORT: 5432
            DB_DATABASE: recipe-book
            DB_USERNAME: chef
            DB_PASSWORD: SUPERsecret!!!:-)
    postgres:
        image: postgres:14
        #    build: ./postgres
        environment:
            POSTGRES_USER: chef
            POSTGRES_PASSWORD: SUPERsecret!!!:-)
            POSTGRES_DB: recipe-book
            POSTGRES_HOST: postgres
        ports:
            - "5432:5432"
    web:
        image: nginx:latest
        ports:
            - "8000:80"
        depends_on:
            - app
        volumes:
            - ./public:/var/www/html/public
            - ./site.conf:/etc/nginx/conf.d/default.conf:ro
